
###
// GET plants
GET http://localhost:3000/api/plants

###
// Get plant by id
GET http://localhost:3000/api/plants/1

###
// POST create a new plant
POST http://localhost:3000/api/plants
Content-Type: application/json

{
  "name": "Liliasdom",
  "species": "vibrág",
  "water_interval_days": "5"
}

###
// PATCH plant by id

PATCH http://localhost:3000/api/plants/1
Content-Type: application/json

{
  "name": "Kaktuszos",
  "species": "sivatagos",
  "water_interval_days": "10"
}

###
// DELETE plant by id
DELETE http://localhost:3000/api/plants/2

###